{
  "mixed-port": 7890,
  "allow-lan": false,
  "unified-delay": false,
  "log-level": "silent",
  "mode": "rule",
  "tcp-concurrent": true,
  "geo-auto-update": true,
  "geo-update-interval": 168,
  "external-controller": "127.0.0.1:9090",
  "external-ui": "ui",
  "profile": {
    "store-selected": true,
    "store-fake-ip": true
  },
  "tun": {
    "enable": true,
    "stack": "mixed",
    "auto-route": true,
    "strict-route": true,
    "auto-detect-interface": true,
    "dns-hijack": [
      "any:53",
      "tcp://any:53"
    ],
    "mtu": 9000
  },
  "sniffer": {
    "enable": true,
    "force-dns-mapping": true,
    "parse-pure-ip": true,
    "override-destination": true,
    "sniff": {
      "HTTP": {
        "ports": [
          80,
          8080
        ]
      },
      "TLS": {
        "ports": [
          443,
          8443,
          2053,
          2083,
          2087,
          2096
        ]
      }
    }
  },
  "dns": {
    "enable": true,
    "respect-rules": true,
    "use-system-hosts": false,
    "listen": "127.0.0.1:1053",
    "ipv6": false,
    "nameserver": [
      "https://8.8.8.8/dns-query#✅ Anonymous Multi"
    ],
    "proxy-server-nameserver": [
      "8.8.8.8#DIRECT"
    ],
    "direct-nameserver": [
      "8.8.8.8#DIRECT"
    ],
    "direct-nameserver-follow-policy": true,
    "nameserver-policy": {
      "rule-set:geosite-ir": "8.8.8.8#DIRECT"
    },
    "enhanced-mode": "fake-ip",
    "fake-ip-range": "198.18.0.1/16",
    "fake-ip-filter-mode": "blacklist",
    "fake-ip-filter": [
      "+.lan",
      "+.local"
    ]
  },
  "proxies": [
    {
      "name": "🇬🇧 9 - GB - VLESS/REALITY/PBK/VISION/UTLS - 8443",
      "type": "vless",
      "server": "31.58.181.88",
      "port": 8443,
      "uuid": "010158f4-1a88-4dfa-8420-c770dc1584e1",
      "network": "tcp",
      "flow": "xtls-rprx-vision",
      "tls": true,
      "servername": "tradingview.com",
      "skip-cert-verify": false,
      "client-fingerprint": "firefox",
      "reality-opts": {
        "public-key": "AERbWB2uslqIzm1hSlOZZEH3Y9qg_zlWRRyLfh97kXc",
        "short-id": ""
      }
    },
    {
      "name": "🇯🇵 19 - JP - VLESS/REALITY/PBK/SID/VISION/UTLS - 30203",
      "type": "vless",
      "server": "18.177.61.231",
      "port": 30203,
      "uuid": "0346a35f-8e11-4b33-852d-00fa9c642878",
      "network": "tcp",
      "flow": "xtls-rprx-vision",
      "tls": true,
      "servername": "www.sony.com",
      "skip-cert-verify": false,
      "client-fingerprint": "chrome",
      "reality-opts": {
        "public-key": "dsJ2WwzENgTAgd8okJPXLpwzdsDjU67mBEnhUhgvvTk",
        "short-id": "40150721499a92"
      }
    },
    {
      "name": "🇳🇴 21 - NO - VLESS/REALITY/PBK/SID/VISION/UTLS - 443",
      "type": "vless",
      "server": "151.242.168.239",
      "port": 443,
      "uuid": "03e5f7fb-d569-403b-8740-9e3b4f7dd94a",
      "network": "tcp",
      "flow": "xtls-rprx-vision",
      "tls": true,
      "servername": "frantax.my3cx.de",
      "skip-cert-verify": false,
      "client-fingerprint": "firefox",
      "reality-opts": {
        "public-key": "SiSky02wHz-S0TDHKFTdYhnrlT8Y3CfRsekZlcdLXDY",
        "short-id": "fd55b698ee8c3629"
      }
    },
    {
      "name": "🇺🇸 24 - US - VLESS/WS/TLS/UTLS - 443",
      "type": "vless",
      "server": "104.17.147.22",
      "port": 443,
      "uuid": "0432902e-6604-40cd-bbd0-57ab4e5d909f",
      "network": "ws",
      "ws-opts": {
        "path": "/eyJqdW5rIjoiOENNZnB6WTgiLCJwcm90b2NvbCI6InZsIiwibW9kZSI6InByb3h5aXAiLCJwYW5lbElQcyI6W119",
        "headers": {
          "Host": "bpb-4dc4958b.hxjkcghchv.workers.dev"
        }
      },
      "tls": true,
      "servername": "bPB-4dc4958B.hXjkcgHcHv.woRkeRs.deV",
      "skip-cert-verify": false,
      "client-fingerprint": "chrome",
      "alpn": [
        "http/1.1"
      ]
    },
    {
      "name": "🇺🇸 25 - US - VLESS/WS/TLS/UTLS - 443",
      "type": "vless",
      "server": "104.17.148.22",
      "port": 443,
      "uuid": "0432902e-6604-40cd-bbd0-57ab4e5d909f",
      "network": "ws",
      "ws-opts": {
        "path": "/eyJqdW5rIjoiOENNZnB6WTgiLCJwcm90b2NvbCI6InZsIiwibW9kZSI6InByb3h5aXAiLCJwYW5lbElQcyI6W119",
        "headers": {
          "Host": "bpb-4dc4958b.hxjkcghchv.workers.dev"
        }
      },
      "tls": true,
      "servername": "bPB-4dc4958B.hXjkcgHcHv.woRkeRs.deV",
      "skip-cert-verify": false,
      "client-fingerprint": "chrome",
      "alpn": [
        "http/1.1"
      ]
    },
    {
      "name": "🇺🇸 27 - US - VLESS/WS - 8080",
      "type": "vless",
      "server": "188.114.97.6",
      "port": 8080,
      "uuid": "0432902e-6604-40cd-bbd0-57ab4e5d909f",
      "network": "ws",
      "ws-opts": {
        "path": "/eyJqdW5rIjoiOENNZnB6WTgiLCJwcm90b2NvbCI6InZsIiwibW9kZSI6InByb3h5aXAiLCJwYW5lbElQcyI6W119",
        "headers": {
          "Host": "bpb-4dc4958b.hxjkcghchv.workers.dev"
        }
      }
    },
    {
      "name": "🇸🇪 31 - SE - VLESS/GRPC/REALITY/PBK/SID/UTLS - 443",
      "type": "vless",
      "server": "185.189.46.63",
      "port": 443,
      "uuid": "04d17971-314f-4922-8e91-d03dc2303353",
      "network": "grpc",
      "tls": true,
      "servername": "swe.denditop.site",
      "skip-cert-verify": false,
      "client-fingerprint": "firefox",
      "reality-opts": {
        "public-key": "HZiMehwH6sQf4bDkLiXJ0KslpYqz0mNFwBr34-e6RRM",
        "short-id": "9c2378562188c3cb"
      }
    },
    {
      "name": "🇵🇱 32 - PL - VLESS/REALITY/PBK/SID/VISION/UTLS - 443",
      "type": "vless",
      "server": "193.34.213.10",
      "port": 443,
      "uuid": "04d17971-314f-4922-8e91-d03dc2303353",
      "network": "tcp",
      "flow": "xtls-rprx-vision",
      "tls": true,
      "servername": "plfsdd.dendiboss.org",
      "skip-cert-verify": false,
      "client-fingerprint": "firefox",
      "reality-opts": {
        "public-key": "NtaFdDQFRPxPPIcRc-qyYDbL9mI_miwnaHcdLWvpgmo",
        "short-id": "9c2378562188c3cb"
      }
    },
    {
      "name": "🇰🇿 33 - KZ - VLESS/REALITY/PBK/VISION/UTLS - 443",
      "type": "vless",
      "server": "194.238.41.173",
      "port": 443,
      "uuid": "04d17971-314f-4922-8e91-d03dc2303353",
      "network": "tcp",
      "flow": "xtls-rprx-vision",
      "tls": true,
      "servername": "kz1.dendibase.org",
      "skip-cert-verify": false,
      "client-fingerprint": "firefox",
      "reality-opts": {
        "public-key": "mbvZt-7r8xaJ8gIfPrhukRATKlB8fQNG8AxPLZeZ6Gg",
        "short-id": ""
      }
    },
    {
      "name": "🇭🇰 34 - HK - VLESS/REALITY/PBK/SID/VISION/UTLS - 443",
      "type": "vless",
      "server": "62.60.232.238",
      "port": 443,
      "uuid": "04d17971-314f-4922-8e91-d03dc2303353",
      "network": "tcp",
      "flow": "xtls-rprx-vision",
      "tls": true,
      "servername": "hk.dendiboss.org",
      "skip-cert-verify": false,
      "client-fingerprint": "firefox",
      "reality-opts": {
        "public-key": "lK305DpoHGgXocbC3HwUcAGnVtmJjsFACgJMbAJrUVw",
        "short-id": "fd6a3a70c2350e51"
      }
    },
    {
      "name": "🇺🇸 35 - US - VLESS/REALITY/PBK/SID/VISION/UTLS - 443",
      "type": "vless",
      "server": "84.32.61.143",
      "port": 443,
      "uuid": "04d17971-314f-4922-8e91-d03dc2303353",
      "network": "tcp",
      "flow": "xtls-rprx-vision",
      "tls": true,
      "servername": "uss.denditop.site",
      "skip-cert-verify": false,
      "client-fingerprint": "firefox",
      "reality-opts": {
        "public-key": "ycjPT1HxLy0b9oRp6tW4LBT6RZ6bAk-OkNqBNyhOyEw",
        "short-id": "fd197bbaca6415b0"
      }
    },
    {
      "name": "🇦🇷 37 - AR - VLESS/REALITY/PBK/SID/VISION/UTLS - 443",
      "type": "vless",
      "server": "149.33.19.143",
      "port": 443,
      "uuid": "0530cbe4-d441-402a-be2e-1627beb458f5",
      "network": "tcp",
      "flow": "xtls-rprx-vision",
      "tls": true,
      "servername": "zvukipro.com",
      "skip-cert-verify": false,
      "client-fingerprint": "firefox",
      "reality-opts": {
        "public-key": "SiSky02wHz-S0TDHKFTdYhnrlT8Y3CfRsekZlcdLXDY",
        "short-id": "fd55b698ee8c3629"
      }
    },
    {
      "name": "🇩🇪 38 - DE - VLESS/REALITY/PBK/SID/VISION/UTLS - 443",
      "type": "vless",
      "server": "167.233.219.201",
      "port": 443,
      "uuid": "05bfcbaa-cba0-4bce-9103-09fe3f5f0667",
      "network": "tcp",
      "flow": "xtls-rprx-vision",
      "tls": true,
      "servername": "www.bing.com",
      "skip-cert-verify": false,
      "client-fingerprint": "chrome",
      "reality-opts": {
        "public-key": "3ei2ET7SLe8rAO3KOlUWyXy0U22zb86VNOqUCshRVl8",
        "short-id": "f648da8196bdb32e"
      }
    },
    {
      "name": "🇬🇧 41 - GB - VLESS/REALITY/PBK/SID/VISION/UTLS - 443",
      "type": "vless",
      "server": "78.129.184.117",
      "port": 443,
      "uuid": "06b7fc10-26d9-4430-a7c7-f01131ee625c",
      "network": "tcp",
      "flow": "xtls-rprx-vision",
      "tls": true,
      "servername": "strapi.io",
      "skip-cert-verify": false,
      "client-fingerprint": "firefox",
      "reality-opts": {
        "public-key": "_8LiLlqEXJGXbg_G8KI1fXBlPnRoM3no-0oxxRRMcSw",
        "short-id": "efcfd3c41c1762b0"
      }
    },
    {
      "name": "🇪🇪 43 - EE - VLESS/TLS/UTLS - 8443",
      "type": "vless",
      "server": "94.183.170.135",
      "port": 8443,
      "uuid": "06c4e938-2954-478f-a870-ca1b163e30e9",
      "network": "tcp",
      "tls": true,
      "servername": "estproxy4.lockdwn.com",
      "skip-cert-verify": false,
      "client-fingerprint": "firefox",
      "alpn": [
        "h2",
        "http/1.1"
      ]
    },
    {
      "name": "🇪🇪 45 - EE - VLESS/TLS/UTLS - 8443",
      "type": "vless",
      "server": "estproxy4.lockdwn.com",
      "port": 8443,
      "uuid": "06c4e938-2954-478f-a870-ca1b163e30e9",
      "network": "tcp",
      "tls": true,
      "servername": "estproxy4.lockdwn.com",
      "skip-cert-verify": false,
      "client-fingerprint": "edge",
      "alpn": [
        "h2",
        "http/1.1"
      ]
    },
    {
      "name": "🇫🇷 46 - FR - VLESS/REALITY/PBK/SID/VISION/UTLS - 443",
      "type": "vless",
      "server": "node14.mxvpn.dev",
      "port": 443,
      "uuid": "0772109c-a680-4896-b005-d86513194f96",
      "network": "tcp",
      "flow": "xtls-rprx-vision",
      "tls": true,
      "servername": "node14.mxvpn.dev",
      "skip-cert-verify": false,
      "client-fingerprint": "chrome",
      "reality-opts": {
        "public-key": "TlpXTLz1Y-v8B6q9MX55U6eypjfL0LCSNE5zQP4yRHw",
        "short-id": "bbc68cec8bb8d2e3"
      }
    },
    {
      "name": "🇬🇧 56 - GB - VLESS/REALITY/PBK/VISION/UTLS - 8443",
      "type": "vless",
      "server": "31.58.181.88",
      "port": 8443,
      "uuid": "0817a3bb-c8fb-4ddf-a05e-321565b39cd8",
      "network": "tcp",
      "flow": "xtls-rprx-vision",
      "tls": true,
      "servername": "tradingview.com",
      "skip-cert-verify": false,
      "client-fingerprint": "firefox",
      "reality-opts": {
        "public-key": "AERbWB2uslqIzm1hSlOZZEH3Y9qg_zlWRRyLfh97kXc",
        "short-id": ""
      }
    },
    {
      "name": "🇺🇸 60 - US - VLESS/WS - 8080",
      "type": "vless",
      "server": "188.114.97.6",
      "port": 8080,
      "uuid": "0836463b-214f-4af6-aa85-85a56a62388e",
      "network": "ws",
      "ws-opts": {
        "path": "/8eaZJhRwB5zzDy81",
        "headers": {
          "Host": "d2127A49-flAT-wooD-C4B5.mILia-AkbARpOor.WorkERs.dEV"
        }
      }
    },
    {
      "name": "🇬🇧 63 - GB - VLESS/REALITY/PBK/VISION/UTLS - 8443",
      "type": "vless",
      "server": "31.58.181.88",
      "port": 8443,
      "uuid": "087d9e19-a290-49ed-a9ae-b47ca943bb39",
      "network": "tcp",
      "flow": "xtls-rprx-vision",
      "tls": true,
      "servername": "tradingview.com",
      "skip-cert-verify": false,
      "client-fingerprint": "firefox",
      "reality-opts": {
        "public-key": "AERbWB2uslqIzm1hSlOZZEH3Y9qg_zlWRRyLfh97kXc",
        "short-id": ""
      }
    },
    {
      "name": "🇬🇧 64 - GB - VLESS/REALITY/PBK/SID/VISION/UTLS - 443",
      "type": "vless",
      "server": "109.169.85.139",
      "port": 443,
      "uuid": "08a8b6c8-b668-4b83-97d5-02d4c974d222",
      "network": "tcp",
      "flow": "xtls-rprx-vision",
      "tls": true,
      "servername": "slashdot.org",
      "skip-cert-verify": false,
      "client-fingerprint": "firefox",
      "reality-opts": {
        "public-key": "SiSky02wHz-S0TDHKFTdYhnrlT8Y3CfRsekZlcdLXDY",
        "short-id": "fd55b698ee8c3629"
      }
    }
  ],
  "proxy-groups": [
    {
      "name": "✅ Anonymous Multi",
      "type": "select",
      "proxies": [
        "🚀 Best Ping",
        "🇬🇧 9 - GB - VLESS/REALITY/PBK/VISION/UTLS - 8443",
        "🇯🇵 19 - JP - VLESS/REALITY/PBK/SID/VISION/UTLS - 30203",
        "🇳🇴 21 - NO - VLESS/REALITY/PBK/SID/VISION/UTLS - 443",
        "🇺🇸 24 - US - VLESS/WS/TLS/UTLS - 443",
        "🇺🇸 25 - US - VLESS/WS/TLS/UTLS - 443",
        "🇺🇸 27 - US - VLESS/WS - 8080",
        "🇸🇪 31 - SE - VLESS/GRPC/REALITY/PBK/SID/UTLS - 443",
        "🇵🇱 32 - PL - VLESS/REALITY/PBK/SID/VISION/UTLS - 443",
        "🇰🇿 33 - KZ - VLESS/REALITY/PBK/VISION/UTLS - 443",
        "🇭🇰 34 - HK - VLESS/REALITY/PBK/SID/VISION/UTLS - 443",
        "🇺🇸 35 - US - VLESS/REALITY/PBK/SID/VISION/UTLS - 443",
        "🇦🇷 37 - AR - VLESS/REALITY/PBK/SID/VISION/UTLS - 443",
        "🇩🇪 38 - DE - VLESS/REALITY/PBK/SID/VISION/UTLS - 443",
        "🇬🇧 41 - GB - VLESS/REALITY/PBK/SID/VISION/UTLS - 443",
        "🇪🇪 43 - EE - VLESS/TLS/UTLS - 8443",
        "🇪🇪 45 - EE - VLESS/TLS/UTLS - 8443",
        "🇫🇷 46 - FR - VLESS/REALITY/PBK/SID/VISION/UTLS - 443",
        "🇬🇧 56 - GB - VLESS/REALITY/PBK/VISION/UTLS - 8443",
        "🇺🇸 60 - US - VLESS/WS - 8080",
        "🇬🇧 63 - GB - VLESS/REALITY/PBK/VISION/UTLS - 8443",
        "🇬🇧 64 - GB - VLESS/REALITY/PBK/SID/VISION/UTLS - 443",
        "DIRECT"
      ]
    },
    {
      "name": "🚀 Best Ping",
      "type": "url-test",
      "proxies": [
        "🇬🇧 9 - GB - VLESS/REALITY/PBK/VISION/UTLS - 8443",
        "🇯🇵 19 - JP - VLESS/REALITY/PBK/SID/VISION/UTLS - 30203",
        "🇳🇴 21 - NO - VLESS/REALITY/PBK/SID/VISION/UTLS - 443",
        "🇺🇸 24 - US - VLESS/WS/TLS/UTLS - 443",
        "🇺🇸 25 - US - VLESS/WS/TLS/UTLS - 443",
        "🇺🇸 27 - US - VLESS/WS - 8080",
        "🇸🇪 31 - SE - VLESS/GRPC/REALITY/PBK/SID/UTLS - 443",
        "🇵🇱 32 - PL - VLESS/REALITY/PBK/SID/VISION/UTLS - 443",
        "🇰🇿 33 - KZ - VLESS/REALITY/PBK/VISION/UTLS - 443",
        "🇭🇰 34 - HK - VLESS/REALITY/PBK/SID/VISION/UTLS - 443",
        "🇺🇸 35 - US - VLESS/REALITY/PBK/SID/VISION/UTLS - 443",
        "🇦🇷 37 - AR - VLESS/REALITY/PBK/SID/VISION/UTLS - 443",
        "🇩🇪 38 - DE - VLESS/REALITY/PBK/SID/VISION/UTLS - 443",
        "🇬🇧 41 - GB - VLESS/REALITY/PBK/SID/VISION/UTLS - 443",
        "🇪🇪 43 - EE - VLESS/TLS/UTLS - 8443",
        "🇪🇪 45 - EE - VLESS/TLS/UTLS - 8443",
        "🇫🇷 46 - FR - VLESS/REALITY/PBK/SID/VISION/UTLS - 443",
        "🇬🇧 56 - GB - VLESS/REALITY/PBK/VISION/UTLS - 8443",
        "🇺🇸 60 - US - VLESS/WS - 8080",
        "🇬🇧 63 - GB - VLESS/REALITY/PBK/VISION/UTLS - 8443",
        "🇬🇧 64 - GB - VLESS/REALITY/PBK/SID/VISION/UTLS - 443"
      ],
      "url": "https://www.gstatic.com/generate_204",
      "interval": 180,
      "tolerance": 50
    }
  ],
  "rule-providers": {
    "geosite-malware": {
      "type": "http",
      "format": "text",
      "behavior": "domain",
      "path": "./ruleset/geosite-malware.txt",
      "interval": 86400,
      "url": "https://raw.githubusercontent.com/Chocolate4U/Iran-clash-rules/release/malware.txt"
    },
    "geosite-phishing": {
      "type": "http",
      "format": "text",
      "behavior": "domain",
      "path": "./ruleset/geosite-phishing.txt",
      "interval": 86400,
      "url": "https://raw.githubusercontent.com/Chocolate4U/Iran-clash-rules/release/phishing.txt"
    },
    "geosite-cryptominers": {
      "type": "http",
      "format": "text",
      "behavior": "domain",
      "path": "./ruleset/geosite-cryptominers.txt",
      "interval": 86400,
      "url": "https://raw.githubusercontent.com/Chocolate4U/Iran-clash-rules/release/cryptominers.txt"
    },
    "geosite-ads": {
      "type": "http",
      "format": "text",
      "behavior": "domain",
      "path": "./ruleset/geosite-ads.txt",
      "interval": 86400,
      "url": "https://raw.githubusercontent.com/Chocolate4U/Iran-clash-rules/release/category-ads-all.txt"
    },
    "geosite-ir": {
      "type": "http",
      "format": "text",
      "behavior": "domain",
      "path": "./ruleset/geosite-ir.txt",
      "interval": 86400,
      "url": "https://raw.githubusercontent.com/Chocolate4U/Iran-clash-rules/release/ir.txt"
    },
    "geoip-ir": {
      "type": "http",
      "format": "text",
      "behavior": "ipcidr",
      "path": "./ruleset/geoip-ir.txt",
      "interval": 86400,
      "url": "https://raw.githubusercontent.com/Chocolate4U/Iran-clash-rules/release/ircidr.txt"
    }
  },
  "rules": [
    "GEOIP,lan,DIRECT,no-resolve",
    "NETWORK,udp,REJECT",
    "RULE-SET,geosite-malware,REJECT",
    "RULE-SET,geosite-phishing,REJECT",
    "RULE-SET,geosite-cryptominers,REJECT",
    "RULE-SET,geosite-ads,REJECT",
    "RULE-SET,geosite-ir,DIRECT",
    "RULE-SET,geoip-ir,DIRECT",
    "MATCH,✅ Anonymous Multi"
  ],
  "ntp": {
    "enable": true,
    "server": "time.cloudflare.com",
    "port": 123,
    "interval": 30
  }
}