{
  "mixed-port": 7890,
  "allow-lan": false,
  "unified-delay": false,
  "log-level": "silent",
  "mode": "rule",
  "tcp-concurrent": true,
  "geo-auto-update": true,
  "geo-update-interval": 168,
  "external-controller": "127.0.0.1:9090",
  "external-ui": "ui",
  "profile": {
    "store-selected": true,
    "store-fake-ip": true
  },
  "tun": {
    "enable": true,
    "stack": "mixed",
    "auto-route": true,
    "strict-route": true,
    "auto-detect-interface": true,
    "dns-hijack": [
      "any:53",
      "tcp://any:53"
    ],
    "mtu": 9000
  },
  "sniffer": {
    "enable": true,
    "force-dns-mapping": true,
    "parse-pure-ip": true,
    "override-destination": true,
    "sniff": {
      "HTTP": {
        "ports": [
          80,
          8080
        ]
      },
      "TLS": {
        "ports": [
          443,
          8443,
          2053,
          2083,
          2087,
          2096
        ]
      }
    }
  },
  "dns": {
    "enable": true,
    "respect-rules": true,
    "use-system-hosts": false,
    "listen": "127.0.0.1:1053",
    "ipv6": false,
    "nameserver": [
      "https://8.8.8.8/dns-query#✅ Anonymous Multi"
    ],
    "proxy-server-nameserver": [
      "8.8.8.8#DIRECT"
    ],
    "direct-nameserver": [
      "8.8.8.8#DIRECT"
    ],
    "direct-nameserver-follow-policy": true,
    "nameserver-policy": {
      "rule-set:geosite-ir": "8.8.8.8#DIRECT"
    },
    "enhanced-mode": "fake-ip",
    "fake-ip-range": "198.18.0.1/16",
    "fake-ip-filter-mode": "blacklist",
    "fake-ip-filter": [
      "+.lan",
      "+.local"
    ]
  },
  "proxies": [
    {
      "name": "🇸🇬 48 - SG - VLESS/REALITY/PBK/SID/VISION - 19825 #1",
      "type": "vless",
      "server": "146.235.16.130",
      "port": 19825,
      "uuid": "2d1ad594-80a4-4bfb-87a6-038e39701f51",
      "flow": "xtls-rprx-vision",
      "network": "tcp",
      "tls": true,
      "servername": "sg2-8sb.6121999.dpdns.org",
      "skip-cert-verify": false,
      "client-fingerprint": "chrome",
      "reality-opts": {
        "public-key": "GvvkY8xYb9QjvwvzYq_uNC4tOGd0DCxRnz6770-xgkI",
        "short-id": "6ba85179e30d4fc2"
      }
    },
    {
      "name": "🇺🇸 88 - US - VLESS/REALITY/PBK/SID/VISION/UTLS - 23576 #7",
      "type": "vless",
      "server": "15.204.97.195",
      "port": 23576,
      "uuid": "48ff2b70-e180-582f-8866-d9a2edeed5f5",
      "flow": "xtls-rprx-vision",
      "network": "tcp",
      "tls": true,
      "servername": "fuck.rkn",
      "skip-cert-verify": false,
      "client-fingerprint": "chrome",
      "reality-opts": {
        "public-key": "1y5h2FGWKXTJ9xLPCqPo6Mw7RxoZzh6fGkEQKNxpZ3s",
        "short-id": "01"
      }
    },
    {
      "name": "🇺🇸 89 - US - VLESS/REALITY/PBK/SID/VISION/UTLS - 23576 #8",
      "type": "vless",
      "server": "15.204.97.197",
      "port": 23576,
      "uuid": "48ff2b70-e180-582f-8866-d9a2edeed5f5",
      "flow": "xtls-rprx-vision",
      "network": "tcp",
      "tls": true,
      "servername": "fuck.rkn",
      "skip-cert-verify": false,
      "client-fingerprint": "chrome",
      "reality-opts": {
        "public-key": "1y5h2FGWKXTJ9xLPCqPo6Mw7RxoZzh6fGkEQKNxpZ3s",
        "short-id": "01"
      }
    },
    {
      "name": "🇺🇸 90 - US - VLESS/REALITY/PBK/SID/VISION/UTLS - 23576 #9",
      "type": "vless",
      "server": "15.204.97.198",
      "port": 23576,
      "uuid": "48ff2b70-e180-582f-8866-d9a2edeed5f5",
      "flow": "xtls-rprx-vision",
      "network": "tcp",
      "tls": true,
      "servername": "fuck.rkn",
      "skip-cert-verify": false,
      "client-fingerprint": "chrome",
      "reality-opts": {
        "public-key": "1y5h2FGWKXTJ9xLPCqPo6Mw7RxoZzh6fGkEQKNxpZ3s",
        "short-id": "01"
      }
    },
    {
      "name": "🇺🇸 91 - US - VLESS/REALITY/PBK/SID/VISION/UTLS - 23576 #10",
      "type": "vless",
      "server": "15.204.97.206",
      "port": 23576,
      "uuid": "48ff2b70-e180-582f-8866-d9a2edeed5f5",
      "flow": "xtls-rprx-vision",
      "network": "tcp",
      "tls": true,
      "servername": "fuck.rkn",
      "skip-cert-verify": false,
      "client-fingerprint": "chrome",
      "reality-opts": {
        "public-key": "1y5h2FGWKXTJ9xLPCqPo6Mw7RxoZzh6fGkEQKNxpZ3s",
        "short-id": "01"
      }
    },
    {
      "name": "🇺🇸 92 - US - VLESS/REALITY/PBK/SID/VISION/UTLS - 23576 #11",
      "type": "vless",
      "server": "15.204.97.214",
      "port": 23576,
      "uuid": "48ff2b70-e180-582f-8866-d9a2edeed5f5",
      "flow": "xtls-rprx-vision",
      "network": "tcp",
      "tls": true,
      "servername": "fuck.rkn",
      "skip-cert-verify": false,
      "client-fingerprint": "chrome",
      "reality-opts": {
        "public-key": "1y5h2FGWKXTJ9xLPCqPo6Mw7RxoZzh6fGkEQKNxpZ3s",
        "short-id": "01"
      }
    },
    {
      "name": "🇺🇸 93 - US - VLESS/REALITY/PBK/SID/VISION/UTLS - 23576 #12",
      "type": "vless",
      "server": "15.204.97.216",
      "port": 23576,
      "uuid": "48ff2b70-e180-582f-8866-d9a2edeed5f5",
      "flow": "xtls-rprx-vision",
      "network": "tcp",
      "tls": true,
      "servername": "fuck.rkn",
      "skip-cert-verify": false,
      "client-fingerprint": "chrome",
      "reality-opts": {
        "public-key": "1y5h2FGWKXTJ9xLPCqPo6Mw7RxoZzh6fGkEQKNxpZ3s",
        "short-id": "01"
      }
    },
    {
      "name": "🇺🇸 94 - US - VLESS/REALITY/PBK/SID/VISION/UTLS - 23576 #13",
      "type": "vless",
      "server": "15.204.97.219",
      "port": 23576,
      "uuid": "48ff2b70-e180-582f-8866-d9a2edeed5f5",
      "flow": "xtls-rprx-vision",
      "network": "tcp",
      "tls": true,
      "servername": "fuck.rkn",
      "skip-cert-verify": false,
      "client-fingerprint": "chrome",
      "reality-opts": {
        "public-key": "1y5h2FGWKXTJ9xLPCqPo6Mw7RxoZzh6fGkEQKNxpZ3s",
        "short-id": "01"
      }
    },
    {
      "name": "🇳🇱 95 - NL - VLESS/REALITY/PBK/SID/VISION/UTLS - 23576 #14",
      "type": "vless",
      "server": "51.158.206.103",
      "port": 23576,
      "uuid": "48ff2b70-e180-582f-8866-d9a2edeed5f5",
      "flow": "xtls-rprx-vision",
      "network": "tcp",
      "tls": true,
      "servername": "fuck.rkn",
      "skip-cert-verify": false,
      "client-fingerprint": "chrome",
      "reality-opts": {
        "public-key": "1y5h2FGWKXTJ9xLPCqPo6Mw7RxoZzh6fGkEQKNxpZ3s",
        "short-id": "01"
      }
    },
    {
      "name": "🇳🇱 96 - NL - VLESS/REALITY/PBK/SID/VISION/UTLS - 23576 #15",
      "type": "vless",
      "server": "51.158.206.12",
      "port": 23576,
      "uuid": "48ff2b70-e180-582f-8866-d9a2edeed5f5",
      "flow": "xtls-rprx-vision",
      "network": "tcp",
      "tls": true,
      "servername": "fuck.rkn",
      "skip-cert-verify": false,
      "client-fingerprint": "chrome",
      "reality-opts": {
        "public-key": "1y5h2FGWKXTJ9xLPCqPo6Mw7RxoZzh6fGkEQKNxpZ3s",
        "short-id": "01"
      }
    },
    {
      "name": "🇳🇱 97 - NL - VLESS/REALITY/PBK/SID/VISION - 23576 #16",
      "type": "vless",
      "server": "51.158.206.19",
      "port": 23576,
      "uuid": "48ff2b70-e180-582f-8866-d9a2edeed5f5",
      "flow": "xtls-rprx-vision",
      "network": "tcp",
      "tls": true,
      "servername": "fuck.rkn",
      "skip-cert-verify": false,
      "client-fingerprint": "chrome",
      "reality-opts": {
        "public-key": "1y5h2FGWKXTJ9xLPCqPo6Mw7RxoZzh6fGkEQKNxpZ3s",
        "short-id": "01"
      }
    },
    {
      "name": "🇳🇱 98 - NL - VLESS/REALITY/PBK/SID/VISION - 23576 #17",
      "type": "vless",
      "server": "51.158.206.20",
      "port": 23576,
      "uuid": "48ff2b70-e180-582f-8866-d9a2edeed5f5",
      "flow": "xtls-rprx-vision",
      "network": "tcp",
      "tls": true,
      "servername": "fuck.rkn",
      "skip-cert-verify": false,
      "client-fingerprint": "chrome",
      "reality-opts": {
        "public-key": "1y5h2FGWKXTJ9xLPCqPo6Mw7RxoZzh6fGkEQKNxpZ3s",
        "short-id": "01"
      }
    },
    {
      "name": "🇳🇱 99 - NL - VLESS/REALITY/PBK/SID/VISION - 23576 #18",
      "type": "vless",
      "server": "51.158.206.25",
      "port": 23576,
      "uuid": "48ff2b70-e180-582f-8866-d9a2edeed5f5",
      "flow": "xtls-rprx-vision",
      "network": "tcp",
      "tls": true,
      "servername": "fuck.rkn",
      "skip-cert-verify": false,
      "client-fingerprint": "chrome",
      "reality-opts": {
        "public-key": "1y5h2FGWKXTJ9xLPCqPo6Mw7RxoZzh6fGkEQKNxpZ3s",
        "short-id": "01"
      }
    },
    {
      "name": "🇳🇱 100 - NL - VLESS/REALITY/PBK/SID/VISION - 23576 #19",
      "type": "vless",
      "server": "51.158.206.26",
      "port": 23576,
      "uuid": "48ff2b70-e180-582f-8866-d9a2edeed5f5",
      "flow": "xtls-rprx-vision",
      "network": "tcp",
      "tls": true,
      "servername": "fuck.rkn",
      "skip-cert-verify": false,
      "client-fingerprint": "chrome",
      "reality-opts": {
        "public-key": "1y5h2FGWKXTJ9xLPCqPo6Mw7RxoZzh6fGkEQKNxpZ3s",
        "short-id": "01"
      }
    },
    {
      "name": "🇳🇱 101 - NL - VLESS/REALITY/PBK/SID/VISION - 23576 #20",
      "type": "vless",
      "server": "51.158.206.29",
      "port": 23576,
      "uuid": "48ff2b70-e180-582f-8866-d9a2edeed5f5",
      "flow": "xtls-rprx-vision",
      "network": "tcp",
      "tls": true,
      "servername": "fuck.rkn",
      "skip-cert-verify": false,
      "client-fingerprint": "chrome",
      "reality-opts": {
        "public-key": "1y5h2FGWKXTJ9xLPCqPo6Mw7RxoZzh6fGkEQKNxpZ3s",
        "short-id": "01"
      }
    },
    {
      "name": "🇳🇱 102 - NL - VLESS/REALITY/PBK/SID/VISION - 23576 #21",
      "type": "vless",
      "server": "51.158.206.34",
      "port": 23576,
      "uuid": "48ff2b70-e180-582f-8866-d9a2edeed5f5",
      "flow": "xtls-rprx-vision",
      "network": "tcp",
      "tls": true,
      "servername": "fuck.rkn",
      "skip-cert-verify": false,
      "client-fingerprint": "chrome",
      "reality-opts": {
        "public-key": "1y5h2FGWKXTJ9xLPCqPo6Mw7RxoZzh6fGkEQKNxpZ3s",
        "short-id": "01"
      }
    },
    {
      "name": "🇳🇱 103 - NL - VLESS/REALITY/PBK/SID/VISION/UTLS - 23576 #22",
      "type": "vless",
      "server": "51.158.206.80",
      "port": 23576,
      "uuid": "48ff2b70-e180-582f-8866-d9a2edeed5f5",
      "flow": "xtls-rprx-vision",
      "network": "tcp",
      "tls": true,
      "servername": "fuck.rkn",
      "skip-cert-verify": false,
      "client-fingerprint": "chrome",
      "reality-opts": {
        "public-key": "1y5h2FGWKXTJ9xLPCqPo6Mw7RxoZzh6fGkEQKNxpZ3s",
        "short-id": "01"
      }
    },
    {
      "name": "🇳🇱 104 - NL - VLESS/REALITY/PBK/SID/VISION - 23576 #23",
      "type": "vless",
      "server": "51.158.206.86",
      "port": 23576,
      "uuid": "48ff2b70-e180-582f-8866-d9a2edeed5f5",
      "flow": "xtls-rprx-vision",
      "network": "tcp",
      "tls": true,
      "servername": "fuck.rkn",
      "skip-cert-verify": false,
      "client-fingerprint": "chrome",
      "reality-opts": {
        "public-key": "1y5h2FGWKXTJ9xLPCqPo6Mw7RxoZzh6fGkEQKNxpZ3s",
        "short-id": "01"
      }
    },
    {
      "name": "🇳🇱 105 - NL - VLESS/REALITY/PBK/SID/VISION - 23576 #24",
      "type": "vless",
      "server": "51.158.206.87",
      "port": 23576,
      "uuid": "48ff2b70-e180-582f-8866-d9a2edeed5f5",
      "flow": "xtls-rprx-vision",
      "network": "tcp",
      "tls": true,
      "servername": "fuck.rkn",
      "skip-cert-verify": false,
      "client-fingerprint": "chrome",
      "reality-opts": {
        "public-key": "1y5h2FGWKXTJ9xLPCqPo6Mw7RxoZzh6fGkEQKNxpZ3s",
        "short-id": "01"
      }
    },
    {
      "name": "🇺🇸 113 - US - VLESS/REALITY/PBK/SID/VISION - 23576 #32",
      "type": "vless",
      "server": "ww13.levikogjgfdd.ir",
      "port": 23576,
      "uuid": "48ff2b70-e180-582f-8866-d9a2edeed5f5",
      "flow": "xtls-rprx-vision",
      "network": "tcp",
      "tls": true,
      "servername": "fuck.rkn",
      "skip-cert-verify": false,
      "client-fingerprint": "chrome",
      "reality-opts": {
        "public-key": "1y5h2FGWKXTJ9xLPCqPo6Mw7RxoZzh6fGkEQKNxpZ3s",
        "short-id": "01"
      }
    },
    {
      "name": "🇰🇷 9 - KR - Trojan/TLS - 443 #1",
      "type": "trojan",
      "server": "noted-cougar.rooster465.autos",
      "port": 443,
      "password": "UX82473651",
      "sni": "noted-cougar.rooster465.autos",
      "skip-cert-verify": false,
      "client-fingerprint": "chrome",
      "alpn": [
        "h2",
        "http/1.1"
      ]
    },
    {
      "name": "🇸🇬 19 - SG - VMess - 18000 #2",
      "type": "vmess",
      "server": "149.88.23.207",
      "port": 18000,
      "uuid": "f8c8dc3d-0d37-46b0-8b34-a7232882fcfe",
      "alterId": 0,
      "cipher": "auto",
      "network": "tcp"
    },
    {
      "name": "🇸🇬 32 - SG - VMess - 18000 #3",
      "type": "vmess",
      "server": "ww11.levikogjgfdd.ir",
      "port": 18000,
      "uuid": "f8c8dc3d-0d37-46b0-8b34-a7232882fcfe",
      "alterId": 0,
      "cipher": "auto",
      "network": "tcp"
    }
  ],
  "proxy-groups": [
    {
      "name": "✅ Anonymous Multi",
      "type": "select",
      "proxies": [
        "🚀 Best Ping",
        "🇸🇬 48 - SG - VLESS/REALITY/PBK/SID/VISION - 19825 #1",
        "🇺🇸 88 - US - VLESS/REALITY/PBK/SID/VISION/UTLS - 23576 #7",
        "🇺🇸 89 - US - VLESS/REALITY/PBK/SID/VISION/UTLS - 23576 #8",
        "🇺🇸 90 - US - VLESS/REALITY/PBK/SID/VISION/UTLS - 23576 #9",
        "🇺🇸 91 - US - VLESS/REALITY/PBK/SID/VISION/UTLS - 23576 #10",
        "🇺🇸 92 - US - VLESS/REALITY/PBK/SID/VISION/UTLS - 23576 #11",
        "🇺🇸 93 - US - VLESS/REALITY/PBK/SID/VISION/UTLS - 23576 #12",
        "🇺🇸 94 - US - VLESS/REALITY/PBK/SID/VISION/UTLS - 23576 #13",
        "🇳🇱 95 - NL - VLESS/REALITY/PBK/SID/VISION/UTLS - 23576 #14",
        "🇳🇱 96 - NL - VLESS/REALITY/PBK/SID/VISION/UTLS - 23576 #15",
        "🇳🇱 97 - NL - VLESS/REALITY/PBK/SID/VISION - 23576 #16",
        "🇳🇱 98 - NL - VLESS/REALITY/PBK/SID/VISION - 23576 #17",
        "🇳🇱 99 - NL - VLESS/REALITY/PBK/SID/VISION - 23576 #18",
        "🇳🇱 100 - NL - VLESS/REALITY/PBK/SID/VISION - 23576 #19",
        "🇳🇱 101 - NL - VLESS/REALITY/PBK/SID/VISION - 23576 #20",
        "🇳🇱 102 - NL - VLESS/REALITY/PBK/SID/VISION - 23576 #21",
        "🇳🇱 103 - NL - VLESS/REALITY/PBK/SID/VISION/UTLS - 23576 #22",
        "🇳🇱 104 - NL - VLESS/REALITY/PBK/SID/VISION - 23576 #23",
        "🇳🇱 105 - NL - VLESS/REALITY/PBK/SID/VISION - 23576 #24",
        "🇺🇸 113 - US - VLESS/REALITY/PBK/SID/VISION - 23576 #32",
        "🇰🇷 9 - KR - Trojan/TLS - 443 #1",
        "🇸🇬 19 - SG - VMess - 18000 #2",
        "🇸🇬 32 - SG - VMess - 18000 #3",
        "DIRECT"
      ]
    },
    {
      "name": "🚀 Best Ping",
      "type": "url-test",
      "proxies": [
        "🇸🇬 48 - SG - VLESS/REALITY/PBK/SID/VISION - 19825 #1",
        "🇺🇸 88 - US - VLESS/REALITY/PBK/SID/VISION/UTLS - 23576 #7",
        "🇺🇸 89 - US - VLESS/REALITY/PBK/SID/VISION/UTLS - 23576 #8",
        "🇺🇸 90 - US - VLESS/REALITY/PBK/SID/VISION/UTLS - 23576 #9",
        "🇺🇸 91 - US - VLESS/REALITY/PBK/SID/VISION/UTLS - 23576 #10",
        "🇺🇸 92 - US - VLESS/REALITY/PBK/SID/VISION/UTLS - 23576 #11",
        "🇺🇸 93 - US - VLESS/REALITY/PBK/SID/VISION/UTLS - 23576 #12",
        "🇺🇸 94 - US - VLESS/REALITY/PBK/SID/VISION/UTLS - 23576 #13",
        "🇳🇱 95 - NL - VLESS/REALITY/PBK/SID/VISION/UTLS - 23576 #14",
        "🇳🇱 96 - NL - VLESS/REALITY/PBK/SID/VISION/UTLS - 23576 #15",
        "🇳🇱 97 - NL - VLESS/REALITY/PBK/SID/VISION - 23576 #16",
        "🇳🇱 98 - NL - VLESS/REALITY/PBK/SID/VISION - 23576 #17",
        "🇳🇱 99 - NL - VLESS/REALITY/PBK/SID/VISION - 23576 #18",
        "🇳🇱 100 - NL - VLESS/REALITY/PBK/SID/VISION - 23576 #19",
        "🇳🇱 101 - NL - VLESS/REALITY/PBK/SID/VISION - 23576 #20",
        "🇳🇱 102 - NL - VLESS/REALITY/PBK/SID/VISION - 23576 #21",
        "🇳🇱 103 - NL - VLESS/REALITY/PBK/SID/VISION/UTLS - 23576 #22",
        "🇳🇱 104 - NL - VLESS/REALITY/PBK/SID/VISION - 23576 #23",
        "🇳🇱 105 - NL - VLESS/REALITY/PBK/SID/VISION - 23576 #24",
        "🇺🇸 113 - US - VLESS/REALITY/PBK/SID/VISION - 23576 #32",
        "🇰🇷 9 - KR - Trojan/TLS - 443 #1",
        "🇸🇬 19 - SG - VMess - 18000 #2",
        "🇸🇬 32 - SG - VMess - 18000 #3"
      ],
      "url": "https://www.gstatic.com/generate_204",
      "interval": 180,
      "tolerance": 50
    }
  ],
  "rule-providers": {
    "geosite-malware": {
      "type": "http",
      "format": "text",
      "behavior": "domain",
      "path": "./ruleset/geosite-malware.txt",
      "interval": 86400,
      "url": "https://raw.githubusercontent.com/Chocolate4U/Iran-clash-rules/release/malware.txt"
    },
    "geosite-phishing": {
      "type": "http",
      "format": "text",
      "behavior": "domain",
      "path": "./ruleset/geosite-phishing.txt",
      "interval": 86400,
      "url": "https://raw.githubusercontent.com/Chocolate4U/Iran-clash-rules/release/phishing.txt"
    },
    "geosite-cryptominers": {
      "type": "http",
      "format": "text",
      "behavior": "domain",
      "path": "./ruleset/geosite-cryptominers.txt",
      "interval": 86400,
      "url": "https://raw.githubusercontent.com/Chocolate4U/Iran-clash-rules/release/cryptominers.txt"
    },
    "geosite-ads": {
      "type": "http",
      "format": "text",
      "behavior": "domain",
      "path": "./ruleset/geosite-ads.txt",
      "interval": 86400,
      "url": "https://raw.githubusercontent.com/Chocolate4U/Iran-clash-rules/release/category-ads-all.txt"
    },
    "geosite-ir": {
      "type": "http",
      "format": "text",
      "behavior": "domain",
      "path": "./ruleset/geosite-ir.txt",
      "interval": 86400,
      "url": "https://raw.githubusercontent.com/Chocolate4U/Iran-clash-rules/release/ir.txt"
    },
    "geoip-ir": {
      "type": "http",
      "format": "text",
      "behavior": "ipcidr",
      "path": "./ruleset/geoip-ir.txt",
      "interval": 86400,
      "url": "https://raw.githubusercontent.com/Chocolate4U/Iran-clash-rules/release/ircidr.txt"
    }
  },
  "rules": [
    "GEOIP,lan,DIRECT,no-resolve",
    "NETWORK,udp,REJECT",
    "RULE-SET,geosite-malware,REJECT",
    "RULE-SET,geosite-phishing,REJECT",
    "RULE-SET,geosite-cryptominers,REJECT",
    "RULE-SET,geosite-ads,REJECT",
    "RULE-SET,geosite-ir,DIRECT",
    "RULE-SET,geoip-ir,DIRECT",
    "MATCH,✅ Anonymous Multi"
  ],
  "ntp": {
    "enable": true,
    "server": "time.cloudflare.com",
    "port": 123,
    "interval": 30
  }
}