name: Update Proxy Configs

on:
  schedule:
    - cron: '0 0 */3 * *'
  workflow_dispatch:

permissions:
  contents: write

jobs:
  update-configs:
    runs-on: ubuntu-latest
    
    steps:
    - uses: actions/checkout@v4
      with:
        token: ${{ secrets.GITHUB_TOKEN }}
    
    - name: Set up Python
      uses: actions/setup-python@v4
      with:
        python-version: '3.x'
    
    - name: Install dependencies
      run: |
        python -m pip install --upgrade pip
        pip install -r requirements.txt
    
    - name: Install sing-box
      run: |
        curl -fsSLO https://github.com/SagerNet/sing-box/releases/download/v1.12.10/sing-box_1.12.10_linux_amd64.deb
        sudo dpkg -i sing-box_1.12.10_linux_amd64.deb
        sudo apt-get install -f
    
    - name: Create directories
      run: |
        mkdir -p assets
        mkdir -p configs
    
    - name: Run config fetcher
      run: python src/fetch_configs.py
      continue-on-error: true
    
    - name: Convert configs to sing-box format
      run: python src/config_to_singbox.py
    
    - name: Backup original singbox config
      run: |
        if [ -f configs/singbox_configs.json ]; then
          cp configs/singbox_configs.json configs/singbox_configs_all.json
          echo "Original sing-box config backed up"
        fi
    
    - name: Test sing-box configs
      run: python src/config_tester.py configs/singbox_configs_all.json configs/singbox_configs_tested.json 8 10
      continue-on-error: true
    
    - name: Verify tested configs exist
      run: |
        if [ -f configs/singbox_configs_tested.json ] && [ -s configs/singbox_configs_tested.json ]; then
          echo "Tested configs file created successfully"
          tested_count=$(grep -o '"type":' configs/singbox_configs_tested.json | wc -l)
          echo "Found $tested_count outbounds in tested config"
        else
          echo "Warning: Tested configs file is empty or missing"
        fi
    
    - name: Generate charts and reports
      run: python src/generate_charts.py
    
    - name: Update README timestamps
      run: |
        timestamp=$(date +%s)
        sed -i "s/channel_stats_chart\.svg?v=[0-9]*/channel_stats_chart.svg?v=$timestamp/" README*.md
    
    - name: Commit changes
      run: |
        git config --global user.name 'github-actions[bot]'
        git config --global user.email 'github-actions[bot]@users.noreply.github.com'
        git add configs/proxy_configs.txt
        git add configs/singbox_configs_all.json
        git add configs/singbox_configs_tested.json
        git add configs/channel_stats.json
        git add assets/
        git add README*.md
        git diff --staged --quiet || git commit -m "Update configs and stats"
        git push