name: Update Proxy Configs

on:
  schedule:
    - cron: '0 0 */3 * *'
  workflow_dispatch:

permissions:
  contents: write

jobs:
  update-configs:
    runs-on: ubuntu-latest
    
    steps:
    - name: Checkout repository
      uses: actions/checkout@v4
      with:
        token: ${{ secrets.GITHUB_TOKEN }}
    
    - name: Set up Python
      uses: actions/setup-python@v4
      with:
        python-version: '3.x'
    
    - name: Install dependencies
      run: |
        python -m pip install --upgrade pip
        pip install -r requirements.txt
    
    - name: Install sing-box
      run: |
        LATEST_URL=$(curl -s "https://api.github.com/repos/SagerNet/sing-box/releases/latest" | grep "browser_download_url.*linux_amd64.deb" | cut -d : -f 2,3 | tr -d \")
        wget -O sing-box.deb $LATEST_URL
        sudo dpkg -i sing-box.deb
        sudo apt-get install -f
    
    - name: Create directories
      run: |
        mkdir -p assets
        mkdir -p configs
    
    - name: Run config fetcher
      run: python src/fetch_configs.py
      continue-on-error: true
    
    - name: Convert configs to sing-box format
      run: python src/config_to_singbox.py
    
    - name: Backup original sing-box config
      run: |
        if [ -f configs/singbox_configs.json ]; then
          cp configs/singbox_configs.json configs/singbox_configs_all.json
          echo "Original sing-box config backed up to singbox_configs_all.json"
        fi
    
    - name: Test sing-box configs
      run: python src/config_tester.py configs/singbox_configs_all.json configs/singbox_configs_tested.json
      continue-on-error: true
    
    - name: Generate charts and reports
      run: python src/generate_charts.py
      
    - name: Update README timestamps and stats
      run: |
        timestamp=$(date +%s)
        
        sed -i "s/channel_stats_chart\.svg?v=[0-9]*/channel_stats_chart.svg?v=$timestamp/" README.md
        sed -i "s/performance_report\.html?v=[0-9]*/performance_report.html?v=$timestamp/" README.md
        
        sed -i "s/channel_stats_chart\.svg?v=[0-9]*/channel_stats_chart.svg?v=$timestamp/" README_FA.md
        sed -i "s/performance_report\.html?v=[0-9]*/performance_report.html?v=$timestamp/" README_FA.md
        
        sed -i "s/channel_stats_chart\.svg?v=[0-9]*/channel_stats_chart.svg?v=$timestamp/" README_CN.md
        sed -i "s/performance_report\.html?v=[0-9]*/performance_report.html?v=$timestamp/" README_CN.md
        
        sed -i "s/channel_stats_chart\.svg?v=[0-9]*/channel_stats_chart.svg?v=$timestamp/" README_RU.md
        sed -i "s/performance_report\.html?v=[0-9]*/performance_report.html?v=$timestamp/" README_RU.md
    
    - name: Commit and push changes
      run: |
        git config --global user.name 'github-actions[bot]'
        git config --global user.email 'github-actions[bot]@users.noreply.github.com'
        git add configs/proxy_configs.txt
        git add configs/singbox_configs_all.json
        git add configs/singbox_configs_tested.json
        git add configs/channel_stats.json
        git add assets/
        git add README.md
        git add README_FA.md
        git add README_CN.md
        git add README_RU.md
        git commit -m "Update proxy configs, stats and reports" || echo "No changes to commit"
        git push